services:
  - type: web
    name: civicshield-web
    env: python
    buildCommand: pip install -r requirements-production.txt
    startCommand: gunicorn "app.main:create_app()"
    envVars:
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_ANON_KEY
        sync: false
      - key: DATABASE_URI
        sync: false
      - key: SECRET_KEY
        generateValue: true
